
name: Run copy application to server - pull request

on: [pull_request]

env:
  DEPLOY_PATH: .
  DEPLOY_TO_PATH: /var/www/githubactions

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.DEPLOY_PATH }}
          target: ${{ env.DEPLOY_TO_PATH }}/${{ steps.extract_branch.outputs.branch }}