
name: Run build image and pull to dockerhub - pull request

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          env: 'local'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: rmkh/githubactions:latest
          platforms: linux/amd64,linux/arm64,linux/386
          no-cache: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json