
name: Run python lint flake8 - push

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: otusds
          POSTGRES_PASSWORD: otusds
          POSTGRES_DB: otusds
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: 1. Setup python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 2. Install pip
        run: |
          python -m pip install --upgrade pip

      - name: 3. Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

